/**
 * Credential-backed OpenSSH identities for remote hosts: one entered login is
 * stored once, and each later session materializes a DSH-controlled
 * configuration, private key file and `known_hosts` from it.
 *
 * Every generated command addresses a deterministic alias, so a connection
 * never depends on the deployment's own `~/.ssh/config`. Because the runtime
 * requires strict host-key checking, first-use trust is established here: the
 * real endpoint's published keys are scanned and recorded before a connection
 * can succeed, rather than accepted by the client during one.
 *
 * @module @deepseek-ai/dsh-host-credentials
 */

import { spawn } from 'node:child_process'
import { createHash } from 'node:crypto'
import { appendFile, chmod, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { Service, type Context } from '@deepseek-ai/cordis'
import { credentialKey } from '@deepseek-ai/dsh-credentials'
import type { CredentialKey, CredentialRecord } from '@deepseek-ai/dsh-credentials'
import { resolveDshHome } from '@deepseek-ai/dsh-home-paths'
import z from '@deepseek-ai/schemastery'
import type { ControlledSshIdentity, HostKeyEndpoint, HostKeyScanner, RemoteHostLogin, SshHostCredentials } from './types.ts'

export type { ControlledSshIdentity, HostKeyEndpoint, HostKeyScanner, RemoteHostLogin, SshHostCredentials } from './types.ts'

/** Stable plugin name of the SSH host-credentials store. */
export const name = 'ssh-host-credentials'

/** Activation dependency: every record operation runs through the mounted `ctx.credentials`. */
export const inject = ['credentials']

/** Credential-key scope owning every stored login record. */
const SCOPE = 'ssh-host-credentials'

/** Payload version this package writes and the only one it reads. */
const PAYLOAD_VERSION = 1

/** Host name or address: an alphanumeric start, then letters, digits and `.`, `_`, `:`, `-`. */
const HOST_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]*$/u

/** Login user: an alphanumeric start, then letters, digits and `.`, `_`, `-`. */
const USER_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/u

/** Whitespace and control characters forbidden inside a host, a user or an id; `\s` already covers `\u0009`–`\u000d`. */
const FORBIDDEN_TEXT = /[\s\u0000-\u0008\u000e-\u001f\u007f]/u

/** Lowest TCP port a login may name. */
const MIN_PORT = 1

/** Highest TCP port a login may name. */
const MAX_PORT = 65_535

/** Generated directory mode; generated files are owner-only at 0600. */
const DIRECTORY_MODE = 0o700

/** Generated file mode; an explicit chmod follows every write because umask can weaken the create mode. */
const FILE_MODE = 0o600

/** Directory name, under the harness home, holding every generated identity when `stateDir` is omitted. */
const DEFAULT_STATE_DIR_NAME = 'ssh-hosts'

/** Default deadline for one `ssh-keyscan` invocation, in milliseconds; `scanTimeoutMs` overrides it. */
const DEFAULT_SCAN_TIMEOUT_MS = 10_000

/** Highest accepted scan deadline; the platform's timer ceiling. */
const MAX_SCAN_TIMEOUT_MS = 2_147_483_647

/** First line of every generated configuration file. */
const CONFIG_HEADER = '# Generated by dsh-ssh-host-credentials; edit the profile instead.'

/** Plugin config: the local directory every generated file lives under. */
export interface Config {
  /**
   * Absolute local directory holding one generated directory per host; omit it
   * for `<DSH home>/ssh-hosts`, where the harness home is `$DSH_HOME` or
   * `~/.dsh`.
   */
  readonly stateDir?: string
  /** Deadline for one `ssh-keyscan` invocation, in milliseconds; defaults to 10000. */
  readonly scanTimeoutMs?: number
}

/** Config schema: an explicit state directory must be absolute; omitting it derives the harness-home default. */
export const Config: z<Config> = z.object({
  stateDir: z.string().min(1).pattern(/^\//u),
  scanTimeoutMs: z.number().step(1).min(1).max(MAX_SCAN_TIMEOUT_MS).default(DEFAULT_SCAN_TIMEOUT_MS),
})

declare module '@deepseek-ai/cordis' {
  interface Context { sshHostCredentials: SshHostCredentialsService }
}

/**
 * Store one host's login material and materialize its DSH-controlled OpenSSH
 * identity on demand.
 *
 * Validation happens before any file or record write, so a rejected login
 * leaves both the credential store and the state directory untouched.
 */
export class SshHostCredentialsService extends Service implements SshHostCredentials {
  /** Absolute state directory every generated file lives under, derived once at construction. */
  private readonly stateDir: string
  private readonly scanner: HostKeyScanner

  /**
   * @param ctx - context that owns the service registration.
   * @param config - plugin config; an omitted `stateDir` becomes `<DSH home>/ssh-hosts`.
   * @param scanner - host-key scanner; defaults to the local `ssh-keyscan` runner.
   */
  constructor(ctx: Context, config: Config, scanner: HostKeyScanner = createSshKeyscanRunner(config)) {
    super(ctx, 'sshHostCredentials')
    this.stateDir = config.stateDir ?? join(resolveDshHome(), DEFAULT_STATE_DIR_NAME)
    this.scanner = scanner
  }

  /**
   * Write one host's controlled configuration and identity.
   * @param login - host, port, user and optional private key.
   * @returns the identity whose alias addresses that host.
   * @throws when a field is malformed, or a generated file cannot be written.
   */
  async materialize(login: RemoteHostLogin): Promise<ControlledSshIdentity> {
    const resolved = resolveLogin(login)
    const alias = aliasFor(resolved)
    const directory = join(this.stateDir, alias)
    await writeIdentity(directory, alias, resolved)
    return {
      alias,
      configPath: join(directory, 'config'),
      directory,
      knownHostsPath: join(directory, 'known_hosts'),
      dispose: async () => {
        await rm(directory, { recursive: true, force: true })
      },
    }
  }

  /**
   * Store one host's login material so later sessions reuse it without prompting.
   * @param id - the host's registry id.
   * @param login - host, port, user and optional private key.
   * @throws when the id or a login field is malformed, or the credential store rejects the write.
   */
  async store(id: string, login: RemoteHostLogin): Promise<void> {
    const key = this.recordKey(id)
    const resolved = resolveLogin(login)
    await this.ctx.credentials.modifyRecord(key, () => Promise.resolve({
      kind: 'grant',
      payload: { version: PAYLOAD_VERSION, login: resolved },
    }))
  }

  /**
   * The stored login material, or undefined while none is stored.
   * @param id - the host's registry id.
   * @returns the stored login, or `undefined` when this id has no record.
   * @throws when the id is malformed or the stored record is not this package's payload.
   */
  async load(id: string): Promise<RemoteHostLogin | undefined> {
    const key = this.recordKey(id)
    const record = await this.ctx.credentials.readRecord(key)
    return record === undefined ? undefined : readLogin(key, record)
  }

  /**
   * Remove stored material and any materialized files for that id.
   * @param id - the host's registry id.
   * @throws when the id is malformed or the stored record is not this package's payload.
   */
  async forget(id: string): Promise<void> {
    const key = this.recordKey(id)
    const login = await this.load(id)
    await this.ctx.credentials.deleteRecord(key)
    if (login !== undefined) {
      await rm(join(this.stateDir, aliasFor(login)), { recursive: true, force: true })
    }
  }

  /**
   * Append one confirmed host-key line to a materialized identity's `known_hosts`.
   * @param identity - the identity whose `known_hosts` receives the line.
   * @param line - one non-empty, single-line `known_hosts` entry.
   * @throws when the line is empty, spans lines, carries a NUL character, or holds fewer than two fields.
   */
  async pinHostKey(identity: ControlledSshIdentity, line: string): Promise<void> {
    const verified = validatedHostKeyLine(line)
    await appendFile(identity.knownHostsPath, `${verified}\n`, { mode: FILE_MODE })
    await chmod(identity.knownHostsPath, FILE_MODE)
  }

  /**
   * Trust a host's published keys for the first time by scanning the real
   * endpoint and recording what it publishes. Only lines the identity's
   * `known_hosts` does not already carry are appended, so repeated calls for
   * one endpoint change nothing and earlier lines survive untouched.
   * @param identity - the identity whose `known_hosts` receives the keys.
   * @param endpoint - real host and port whose keys are scanned.
   * @throws when the endpoint is malformed, the scan fails, a scanned line is malformed, or the host publishes no key.
   */
  async trustFirstUse(identity: ControlledSshIdentity, endpoint: HostKeyEndpoint): Promise<void> {
    const target = resolveEndpoint(endpoint)
    const scanned = scannedKeys(await this.scanner.scan(target), target)
    if (scanned.length === 0) {
      throw new Error(`ssh-host-credentials: ${target.host}:${String(target.port)} published no host key; check the host name, port and that ssh-keyscan can reach it`)
    }
    const known = new Set(await readKnownHostLines(identity.knownHostsPath))
    const additions = scanned.filter(line => !known.has(line))
    if (additions.length > 0) {
      await appendFile(identity.knownHostsPath, additions.map(line => `${line}\n`).join(''), { mode: FILE_MODE })
    }
    await chmod(identity.knownHostsPath, FILE_MODE)
  }

  /**
   * The credential record key one host id owns.
   * @param id - the host's registry id.
   * @returns the branded `<scope>/<id>` credential key.
   * @throws when the id is empty or carries a separator, whitespace or control character.
   */
  private recordKey(id: string): CredentialKey {
    return credentialKey(SCOPE, validatedId(id))
  }
}

/**
 * Mount the store on a context.
 * @param ctx - context that owns the service registration.
 * @param config - plugin config; an omitted `stateDir` becomes `<DSH home>/ssh-hosts`.
 */
export function apply(ctx: Context, config: Config): void {
  new SshHostCredentialsService(ctx, config)
}

/**
 * Build the default scanner: one local `ssh-keyscan` invocation per endpoint.
 *
 * Unlike a best-effort probe, a scan that exits non-zero, cannot start, or
 * exceeds its deadline rejects; an unconfirmed host key must never be treated
 * as trusted.
 * @param config - store configuration carrying the scan deadline.
 * @returns the scanner used when the caller injects none.
 */
export function createSshKeyscanRunner(config: Config): HostKeyScanner {
  const timeoutMs = config.scanTimeoutMs ?? DEFAULT_SCAN_TIMEOUT_MS
  return {
    /**
     * Scan one endpoint through the local OpenSSH client.
     * @param endpoint - host and port to scan.
     * @returns one line per key the host published.
     * @throws when the scan cannot start, exits non-zero, or exceeds the deadline.
     */
    scan: endpoint => runKeyscan(timeoutMs, endpoint),
  }
}

/**
 * Run one `ssh-keyscan` invocation and collect its output lines.
 * @param timeoutMs - deadline after which the scan is terminated and rejected.
 * @param endpoint - the validated host and port to scan.
 * @returns the scan's output split into lines.
 * @throws when `ssh-keyscan` cannot start, exits non-zero, or exceeds the deadline.
 */
function runKeyscan(timeoutMs: number, endpoint: HostKeyEndpoint): Promise<readonly string[]> {
  return new Promise((resolve, reject) => {
    const args = ['-p', String(endpoint.port), '-T', String(Math.ceil(timeoutMs / 1000)), '-t', 'rsa,ecdsa,ed25519', endpoint.host]
    const child = spawn('ssh-keyscan', args, { stdio: ['ignore', 'pipe', 'pipe'] })
    const stdout: string[] = []
    const stderr: string[] = []
    let timedOut = false
    let settled = false
    child.stdout.setEncoding('utf8')
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (chunk: string) => { stdout.push(chunk) })
    child.stderr.on('data', (chunk: string) => { stderr.push(chunk) })
    const timer = setTimeout(() => { timedOut = true; child.kill('SIGTERM') }, timeoutMs)
    timer.unref()
    const fail = (detail: string): void => {
      clearTimeout(timer)
      if (settled) return
      settled = true
      reject(keyscanFailure(endpoint, detail, stderr.join('')))
    }
    child.once('error', (error: Error) => { fail(`could not start: ${error.message}`) })
    child.once('close', (code) => {
      clearTimeout(timer)
      if (settled) return
      if (timedOut) fail(`did not answer within ${String(timeoutMs)} ms`)
      else if (code !== 0) fail(`exited with code ${String(code ?? 255)}`)
      else { settled = true; resolve(stdout.join('').split('\n')) }
    })
  })
}

/**
 * Reject an endpoint that cannot be a real scan target.
 * @param endpoint - the caller's endpoint.
 * @returns the accepted host and port.
 * @throws when the host cannot be an OpenSSH name or the port is outside the TCP range.
 */
function resolveEndpoint(endpoint: HostKeyEndpoint): HostKeyEndpoint {
  return { host: validatedHost(endpoint.host), port: validatedPort(endpoint.port) }
}

/**
 * Accept every well-formed scanned key line and drop blank and comment lines.
 * @param lines - the scanner's lines.
 * @param endpoint - the scanned endpoint, named in every diagnostic.
 * @returns the accepted `known_hosts` lines.
 * @throws when a key line spans lines, carries a NUL character, or names fewer than three space-separated fields.
 */
function scannedKeys(lines: readonly string[], endpoint: HostKeyEndpoint): string[] {
  const accepted: string[] = []
  for (const raw of lines) {
    const line = raw.trim()
    if (line.length === 0 || line.startsWith('#')) continue
    accepted.push(validatedScannedLine(line, endpoint))
  }
  return accepted
}

/**
 * Reject a scanned line that cannot be one `known_hosts` entry.
 * @param line - a trimmed, non-empty, non-comment line.
 * @param endpoint - the scanned endpoint, named in the diagnostic.
 * @returns the accepted line.
 * @throws when it spans lines, carries a NUL character, or names fewer than three fields.
 */
function validatedScannedLine(line: string, endpoint: HostKeyEndpoint): string {
  const subject = `scanned host key line for ${endpoint.host}:${String(endpoint.port)}`
  if (/[\r\n]/u.test(line)) throw new Error(`ssh-host-credentials: ${subject} ${JSON.stringify(line)} must be a single line`)
  if (line.includes('\u0000')) throw new Error(`ssh-host-credentials: ${subject} must not contain a NUL character`)
  if (line.split(/\s+/u).length < 3) {
    throw new Error(`ssh-host-credentials: ${subject} ${JSON.stringify(line)} must carry at least three space-separated fields`)
  }
  return line
}

/**
 * Read the `known_hosts` lines one identity already records.
 * @param path - absolute `known_hosts` path.
 * @returns the file's lines, or none while the file does not exist.
 * @throws when the file exists but cannot be read.
 */
async function readKnownHostLines(path: string): Promise<string[]> {
  const content = await readFile(path, 'utf8').catch((error: unknown) => {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return ''
    throw error
  })
  return content.split('\n').filter(line => line.length > 0)
}

/**
 * Build the diagnostic for one failed scan.
 * @param endpoint - host and port the scan addressed.
 * @param detail - what the scan did.
 * @param stderr - standard error collected so far.
 * @returns the error naming the endpoint and a bounded stderr fragment.
 */
function keyscanFailure(endpoint: HostKeyEndpoint, detail: string, stderr: string): Error {
  const diagnostics = snippet(stderr)
  return new Error(`ssh-host-credentials: ssh-keyscan ${endpoint.host}:${String(endpoint.port)} ${detail}${diagnostics.length === 0 ? '' : `: ${diagnostics}`}`)
}

/**
 * Bound one diagnostic fragment so an error never echoes a whole scan transcript.
 * @param text - collected command output.
 * @returns at most 200 characters of trimmed output.
 */
function snippet(text: string): string {
  return text.trim().slice(0, 200)
}

/**
 * Validate one login and drop an absent private key, so the returned value
 * carries exactly the fields a caller entered.
 * @param login - the caller's login material.
 * @returns the accepted login.
 * @throws when host, port, user or private key is malformed.
 */
function resolveLogin(login: RemoteHostLogin): RemoteHostLogin {
  const host = validatedHost(login.host)
  const port = validatedPort(login.port)
  const user = validatedUser(login.user)
  if (login.privateKey === undefined) return { host, port, user }
  return { host, port, user, privateKey: validatedPrivateKey(login.privateKey) }
}

/**
 * Reject a host that cannot be an OpenSSH `HostName` word.
 * @param host - candidate host name or address.
 * @returns the accepted host.
 * @throws when it does not start alphanumerically or carries a disallowed character.
 */
function validatedHost(host: string): string {
  if (!HOST_PATTERN.test(host) || FORBIDDEN_TEXT.test(host)) {
    throw new Error(`ssh-host-credentials: host ${JSON.stringify(host)} must start with an alphanumeric and contain only letters, digits, ".", "_", ":" and "-"`)
  }
  return host
}

/**
 * Reject a port outside the TCP range.
 * @param port - candidate TCP port.
 * @returns the accepted port.
 * @throws when it is not an integer from 1 through 65535.
 */
function validatedPort(port: number): number {
  if (!Number.isInteger(port) || port < MIN_PORT || port > MAX_PORT) {
    throw new Error(`ssh-host-credentials: port ${JSON.stringify(port)} must be an integer from ${String(MIN_PORT)} through ${String(MAX_PORT)}`)
  }
  return port
}

/**
 * Reject a user that cannot be an OpenSSH `User` word.
 * @param user - candidate login user.
 * @returns the accepted user.
 * @throws when it does not start alphanumerically or carries a disallowed character.
 */
function validatedUser(user: string): string {
  if (!USER_PATTERN.test(user) || FORBIDDEN_TEXT.test(user)) {
    throw new Error(`ssh-host-credentials: user ${JSON.stringify(user)} must start with an alphanumeric and contain only letters, digits, ".", "_" and "-"`)
  }
  return user
}

/**
 * Reject private key text that cannot be an armored key. The content itself is
 * never echoed, so a rejected secret cannot reach a log or an error message.
 * @param privateKey - candidate armored private key text.
 * @returns the accepted key text.
 * @throws when it is empty, carries a NUL character, or lacks the `PRIVATE KEY` marker.
 */
function validatedPrivateKey(privateKey: string): string {
  if (privateKey.length === 0) {
    throw new Error('ssh-host-credentials: privateKey must not be empty; omit it to authenticate through the environment\'s agent and default keys')
  }
  if (privateKey.includes('\u0000')) {
    throw new Error('ssh-host-credentials: privateKey must not contain a NUL character')
  }
  if (!privateKey.includes('PRIVATE KEY')) {
    throw new Error('ssh-host-credentials: privateKey must contain the "PRIVATE KEY" marker of an armored key')
  }
  return privateKey
}

/**
 * Reject a host id this package cannot address a record by.
 * @param id - candidate registry id.
 * @returns the accepted id.
 * @throws when it is empty or carries a path separator, whitespace or control character.
 */
function validatedId(id: string): string {
  if (id.length === 0 || id.includes('/') || id.includes('\\') || FORBIDDEN_TEXT.test(id)) {
    throw new Error(`ssh-host-credentials: host id ${JSON.stringify(id)} must be non-empty and contain no "/", "\\", whitespace or control character`)
  }
  return id
}

/**
 * Reject a line that cannot be one `known_hosts` entry.
 * @param line - candidate host-key line.
 * @returns the accepted line.
 * @throws when it is empty, spans lines, carries a NUL character, or names fewer than two fields.
 */
function validatedHostKeyLine(line: string): string {
  if (line.length === 0) throw new Error('ssh-host-credentials: host key line must not be empty')
  if (/[\r\n]/u.test(line)) throw new Error(`ssh-host-credentials: host key line ${JSON.stringify(line)} must be a single line`)
  if (line.includes('\u0000')) throw new Error('ssh-host-credentials: host key line must not contain a NUL character')
  if (line.trim().split(/\s+/u).length < 2) {
    throw new Error(`ssh-host-credentials: host key line ${JSON.stringify(line)} must carry at least two space-separated fields`)
  }
  return line
}

/**
 * Derive the deterministic OpenSSH alias one login addresses.
 * @param login - the validated login material.
 * @returns `dsh-` plus the first 16 lowercase hex digits of `sha256(host\0port\0user)`.
 */
function aliasFor(login: RemoteHostLogin): string {
  const digest = createHash('sha256')
    .update(`${login.host}\u0000${String(login.port)}\u0000${login.user}`, 'utf8')
    .digest('hex')
  return `dsh-${digest.slice(0, 16)}`
}

/**
 * Render the generated OpenSSH configuration for one login.
 * @param alias - the alias every command addresses.
 * @param login - the validated login material.
 * @param identityPath - absolute private key path, absent without a private key.
 * @param knownHostsPath - absolute DSH-controlled `known_hosts` path.
 * @returns the configuration text, ending with a newline.
 */
function configText(
  alias: string,
  login: RemoteHostLogin,
  identityPath: string | undefined,
  knownHostsPath: string,
): string {
  return [
    CONFIG_HEADER,
    `Host ${alias}`,
    `  HostName ${login.host}`,
    `  Port ${String(login.port)}`,
    `  User ${login.user}`,
    ...identityPath === undefined ? [] : [`  IdentityFile ${identityPath}`],
    '  IdentitiesOnly yes',
    '  BatchMode yes',
    '  ForwardAgent no',
    '  ClearAllForwardings yes',
    '  StrictHostKeyChecking accept-new',
    `  UserKnownHostsFile ${knownHostsPath}`,
    '  GlobalKnownHostsFile /dev/null',
    '  ServerAliveInterval 10',
    '  ServerAliveCountMax 3',
    '',
  ].join('\n')
}

/**
 * Normalize armored key text for the private key file.
 * @param privateKey - the validated key text.
 * @returns the text with CRLF line endings replaced and exactly one trailing newline.
 */
function normalizedKeyText(privateKey: string): string {
  const normalized = privateKey.replaceAll('\r\n', '\n')
  return normalized.endsWith('\n') ? normalized : `${normalized}\n`
}

/**
 * Replace one host's generated directory with a freshly written identity.
 * @param directory - absolute `<stateDir>/<alias>` directory to replace.
 * @param alias - the alias the generated configuration defines.
 * @param login - the validated login material.
 * @throws when a file or the directory cannot be written.
 */
async function writeIdentity(directory: string, alias: string, login: RemoteHostLogin): Promise<void> {
  await rm(directory, { recursive: true, force: true })
  await mkdir(directory, { recursive: true, mode: DIRECTORY_MODE })
  const privateKey = login.privateKey
  const identityPath = privateKey === undefined ? undefined : join(directory, 'identity')
  const knownHostsPath = join(directory, 'known_hosts')
  if (privateKey !== undefined && identityPath !== undefined) {
    await writeFile(identityPath, normalizedKeyText(privateKey), { mode: FILE_MODE })
    await chmod(identityPath, FILE_MODE)
  }
  await writeFile(knownHostsPath, '', { mode: FILE_MODE })
  await chmod(knownHostsPath, FILE_MODE)
  const configPath = join(directory, 'config')
  await writeFile(configPath, configText(alias, login, identityPath, knownHostsPath), { mode: FILE_MODE })
  await chmod(configPath, FILE_MODE)
}

/**
 * Read one stored record back into login material.
 * @param key - the record's credential key, named in every diagnostic.
 * @param record - the record as the credential store returned it.
 * @returns the stored login material.
 * @throws when the record is not this package's grant payload.
 */
function readLogin(key: CredentialKey, record: CredentialRecord): RemoteHostLogin {
  if (record.kind !== 'grant') {
    throw new Error(`ssh-host-credentials: record ${key} must be a grant record carrying payload version ${String(PAYLOAD_VERSION)}, found kind ${JSON.stringify(record.kind)}`)
  }
  const payload: unknown = record.payload
  const expected = `record ${key} payload version ${String(PAYLOAD_VERSION)}`
  if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) {
    throw new Error(`ssh-host-credentials: ${expected} must be an object carrying "login"`)
  }
  const version: unknown = (payload as { version?: unknown }).version
  if (version !== PAYLOAD_VERSION) {
    throw new Error(`ssh-host-credentials: record ${key} payload version must be ${String(PAYLOAD_VERSION)}; the record carries version ${JSON.stringify(version)}`)
  }
  const login: unknown = (payload as { login?: unknown }).login
  if (typeof login !== 'object' || login === null || Array.isArray(login)) {
    throw new Error(`ssh-host-credentials: ${expected} must carry an object "login"`)
  }
  const fields = login as Record<string, unknown>
  const privateKey = fields.privateKey
  if (typeof fields.host !== 'string' || typeof fields.port !== 'number' || typeof fields.user !== 'string'
    || (privateKey !== undefined && typeof privateKey !== 'string')) {
    throw new Error(`ssh-host-credentials: ${expected} must carry string "login.host", integer "login.port", string "login.user" and optional string "login.privateKey"`)
  }
  return resolveLogin({
    host: fields.host,
    port: fields.port,
    user: fields.user,
    ...privateKey === undefined ? {} : { privateKey },
  })
}
